const $=id=>document.getElementById(id);let mode='login';
function ensureCloud(){
  if(window.LUPIN_CLOUD)return window.LUPIN_CLOUD;
  const C=window.LUPIN_CONFIG||{},cfg=C.cloud||{},apiBase=String(cfg.apiBase||'https://lupin-data-api.lujinsg.workers.dev').replace(/\/$/,''),airline=String(cfg.airline||'lupin-airlines'),key='lupinCloudSession';
  const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
  const save=s=>localStorage.setItem(key,JSON.stringify(s));
  const clear=()=>{localStorage.removeItem(key);try{sessionStorage.removeItem(key)}catch{}};
  async function api(path,options={}){const h=Object.assign({'Content-Type':'application/json'},options.headers||{}),s=read();if(s?.token)h.Authorization='Bearer '+s.token;let r;try{r=await fetch(apiBase+'/api/'+encodeURIComponent(airline)+path,Object.assign({},options,{headers:h,cache:'no-store'}))}catch(e){throw new Error('Could not reach the Lupin cloud. Check your connection and try again.')};let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||'Cloud API error ('+r.status+').');e.status=r.status;throw e}return d}
  async function login(username,password){const d=await api('/login',{method:'POST',body:JSON.stringify({username,password})});save({username:d.username,miles:Number(d.miles||0),token:d.token});return d}
  async function register(username,password){const d=await api('/register',{method:'POST',body:JSON.stringify({username,password})});save({username:d.username,miles:Number(d.miles||0),token:d.token});return d}
  async function account(){if(!read())return null;try{return await api('/me')}catch(e){if(e.status===401)clear();throw e}}
  async function bookings(){if(!read())return [];return (await api('/bookings')).bookings||[]}
  async function book(data){return api('/bookings',{method:'POST',body:JSON.stringify(data)})}
  async function cancel(id){return api('/bookings/'+encodeURIComponent(id)+'/cancel',{method:'POST'})}
  async function flights(){return (await api('/flights')).flights||[]}
  return window.LUPIN_CLOUD={apiBase,airline,current:()=>read()?.username||'',session:read,logout:clear,login,register,account,bookings,book,cancel,flights};
}
const cloud=ensureCloud();
function showMode(next){mode=next;$('loginTab').classList.toggle('active',mode==='login');$('registerTab').classList.toggle('active',mode==='register');$('authButton').textContent=mode==='login'?'Log in':'Create account';$('authStatus').textContent=''}
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#39;'}[c]))}
function showLoggedIn(a){$('authCard').classList.add('hidden');$('accountCard').classList.remove('hidden');$('accountName').textContent=a.username;$('milesBalance').textContent=Number(a.miles||0).toLocaleString()}
async function showAccount(){try{const a=await cloud.account();if(!a){$('authCard').classList.remove('hidden');$('accountCard').classList.add('hidden');return}showLoggedIn(a);await renderBookings()}catch(e){$('authStatus').textContent='❌ '+e.message}}
async function renderBookings(){const list=await cloud.bookings(),box=$('bookings');$('bookingsStatus').textContent=list.length+' booking(s) found.';if(!list.length){box.innerHTML='<div class="empty">No bookings on this account yet. <a href="../booking/">Book a flight →</a></div>';return}box.innerHTML=list.map(b=>`<article class="booking"><h3>${escapeHtml(b.bookingId)} · ${escapeHtml(b.flight)}</h3><p><strong>${escapeHtml(b.destination)}</strong></p><p class="muted">📅 ${escapeHtml(b.date)} · 🕒 ${escapeHtml(b.time)} · 🚪 Gate ${escapeHtml(b.gate)}<br>👤 ${escapeHtml(b.passengers)} · 💰 S$${Number(b.fare||0).toLocaleString()}</p><p><strong>Status: ${escapeHtml(b.status)}</strong></p>${b.status==='Cancelled'?'':'<button class="cancel" type="button" data-id="'+escapeHtml(b.bookingId)+'">Cancel booking</button>'}</article>`).join('');box.querySelectorAll('.cancel').forEach(x=>x.addEventListener('click',()=>cancelBooking(x.dataset.id)))}
function logout(){cloud.logout();location.reload()}async function cancelBooking(id){try{await cloud.cancel(id);await showAccount()}catch(e){$('bookingsStatus').textContent='❌ '+e.message}}
async function submitAuth(e){e.preventDefault();const username=$('username').value.trim(),password=$('password').value;if(!/^[A-Za-z0-9_-]{3,20}$/.test(username)){$('authStatus').textContent='❌ Username must be 3–20 letters, numbers, _ or -.';return}if(password.length<6){$('authStatus').textContent='❌ Password must be at least 6 characters.';return}try{$('authButton').disabled=true;$('authStatus').textContent=mode==='login'?'Logging in…':'Creating account…';const a=mode==='login'?await cloud.login(username,password):await cloud.register(username,password);showLoggedIn(a);await renderBookings()}catch(e){$('authStatus').textContent='❌ '+e.message}finally{$('authButton').disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{$('loginTab').addEventListener('click',()=>showMode('login'));$('registerTab').addEventListener('click',()=>showMode('register'));$('authForm').addEventListener('submit',submitAuth);$('logout').addEventListener('click',logout);$('refresh').addEventListener('click',showAccount);showAccount()});
