const $=id=>document.getElementById(id);let mode='login';
const cloud=()=>window.LUPIN_CLOUD;
function showMode(next){mode=next;$('loginTab').classList.toggle('active',mode==='login');$('registerTab').classList.toggle('active',mode==='register');$('authButton').textContent=mode==='login'?'Log in':'Create account';$('authStatus').textContent=''}
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function showLoggedIn(a){$('authCard').classList.add('hidden');$('accountCard').classList.remove('hidden');$('accountName').textContent=a.username;$('milesBalance').textContent=Number(a.miles||0).toLocaleString()}
async function showAccount(){try{const c=cloud();if(!c)throw new Error('Shared cloud client is not ready.');const a=await c.account();if(!a){$('authCard').classList.remove('hidden');$('accountCard').classList.add('hidden');return}showLoggedIn(a);await renderBookings()}catch(e){$('authStatus').textContent='❌ '+e.message}}
async function renderBookings(){const list=await cloud().bookings(),box=$('bookings');$('bookingsStatus').textContent=list.length+' booking(s) found.';if(!list.length){box.innerHTML='<div class="empty">No bookings on this account yet. <a href="../booking/">Book a flight →</a></div>';return}box.innerHTML=list.map(b=>`<article class="booking"><h3>${escapeHtml(b.bookingId)} · ${escapeHtml(b.flight)}</h3><p><strong>${escapeHtml(b.destination)}</strong></p><p class="muted">📅 ${escapeHtml(b.date)} · 🕒 ${escapeHtml(b.time)} · 🚪 Gate ${escapeHtml(b.gate)}<br>👤 ${escapeHtml(b.passengers)} · 💰 S$${Number(b.fare||0).toLocaleString()}</p><p><strong>Status: ${escapeHtml(b.status)}</strong></p>${b.status==='Cancelled'?'':'<button class="cancel" type="button" data-id="'+escapeHtml(b.bookingId)+'">Cancel booking</button>'}</article>`).join('');box.querySelectorAll('.cancel').forEach(x=>x.addEventListener('click',()=>cancelBooking(x.dataset.id)))}
function logout(){cloud().logout();location.reload()}async function cancelBooking(id){try{await cloud().cancel(id);await showAccount()}catch(e){$('bookingsStatus').textContent='❌ '+e.message}}
async function submitAuth(e){e.preventDefault();const username=$('username').value.trim(),password=$('password').value;if(!/^[A-Za-z0-9_-]{3,20}$/.test(username)){$('authStatus').textContent='❌ Username must be 3–20 letters, numbers, _ or -.';return}if(password.length<6){$('authStatus').textContent='❌ Password must be at least 6 characters.';return}try{$('authButton').disabled=true;$('authStatus').textContent=mode==='login'?'Logging in…':'Creating account…';const c=cloud();if(!c)throw new Error('Shared cloud client is not ready.');const a=mode==='login'?await c.login(username,password):await c.register(username,password);showLoggedIn(a);await renderBookings()}catch(e){$('authStatus').textContent='❌ '+e.message}finally{$('authButton').disabled=false}}
document.addEventListener('DOMContentLoaded',()=>{$('loginTab').addEventListener('click',()=>showMode('login'));$('registerTab').addEventListener('click',()=>showMode('register'));$('authForm').addEventListener('submit',submitAuth);$('logout').addEventListener('click',logout);$('refresh').addEventListener('click',showAccount);showAccount()});